
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2026-Current ParentElement, LLC. All Rights Reserved")]
[assembly: AssemblyVersion("0.4.166")]
[assembly: AssemblyFileVersion("0.4.166")]
[assembly: AssemblyCompany("ParentElement, LLC")]
[assembly: AssemblyProduct("ParentElement.Topten.RichTextKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2023, 8, 21, 4, 26, 41, DateTimeKind.Utc);
}
	